export const teams = [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Bournemouth",
    "Brighton & Hove Albion",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    'Leed United',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle',
    'Nottingham Forest',
    'Southampton',
    'Tottenham',
    'West Ham United',
    'Wolverhampton'
];